Repository Planning-Inspectorate/appeal-planning-decision, pull requests merged in 2021-03, with the labels that each got.

#600 Subtask/as 87 task status
  packages/lpa-questionnaire-web-app/src/services/task-status/extra-conditions.js
  packages/lpa-questionnaire-web-app/src/services/task.service.js
  packages/lpa-questionnaire-web-app/tests/unit/services/task-status/extra-conditions.test.js
Labels: please-review-me

#608 chore: add flux and openfaas namespaces to the rbac configuration
  infrastructure/k8s/rbac/user.yaml
  infrastructure/k8s/setup.sh
Labels: please-review-me

#599 Subtask/as 86 connect question to form data
  packages/lpa-questionnaire-web-app/src/controllers/extra-conditions.js
  packages/lpa-questionnaire-web-app/src/routes/extra-conditions.js
  packages/lpa-questionnaire-web-app/src/validators/extra-conditions.js
  packages/lpa-questionnaire-web-app/src/views/extra-conditions.njk
  packages/lpa-questionnaire-web-app/tests/unit/controllers/extra-conditions.test.js
  packages/lpa-questionnaire-web-app/tests/unit/validators/extra-conditions.test.js
Labels: please-review-me

#611 ci: ignore runs if CI SKIP appears in commit message
  .github/workflows/documentation-update.yml
  .github/workflows/e2e-tests-on-PR.yml
Labels: please-review-me

#609 chore: configure code ownership rules
  CODEOWNERS
Labels: please-review-me

#615 chore: specify versions for the public Helm charts
  .github/workflows/infra-environments.yml
  infrastructure/k8s/setup.sh
Labels: please-review-me

#623 chore(release): update DOCUMENT_SERVICE_URL to point to correct deployment
  releases/dev/functions.yml
  releases/preprod/functions.yml
Labels: please-review-me

#625 fix(as-1313): add a default value if first/last name not present
  packages/horizon-create-contact/handler.js
  packages/horizon-create-contact/handler.spec.js
Labels: please-review-me

#633 fix(lpa-questionnaire): fix id on extra conditions textarea
  packages/lpa-questionnaire-web-app/src/views/extra-conditions.njk
Labels: please-review-me

#634 chore(semantic-release): stop the changelog and versions being updated on new releases
  .releaserc
Labels: please-review-me

#636 chore: version bump lpa-questionnaire appeal-reply-service pre prod
  releases/preprod/app.yml
Labels: please-review-me

#626 refactor(e2e-tests): refactor e2e tests
  e2e-tests/cypress/integration/appeal-submission-save-and-continue-navigation-appeal-site/appeal-submission-save-and-continue-navigation-appeal-site.js
  e2e-tests/cypress/integration/appeal-submission-tasklist-planningApplicationNumber/appeal-submission-tasklist-planningApplicationNumber.js
  e2e-tests/cypress/integration/appeal-submission-tasklist/appeal-submission-tasklist.js
  e2e-tests/cypress/integration/appellant-confirms-declaration/appellant-confirms-declaration.js
  e2e-tests/cypress/integration/appellant-submission-planning-application-number/appellant-submission-planning-application-number.js
  e2e-tests/cypress/integration/common/appeal-header-footer.js
  e2e-tests/cypress/integration/common/appeal-submission-confirmation.js
  e2e-tests/cypress/integration/common/appellant-submission-check-your-answers.js
  e2e-tests/cypress/integration/common/integration-with-acp.js
  e2e-tests/cypress/support/appellant-submission-check-your-answers/provideCompleteAppeal.js
  e2e-tests/cypress/support/commands-go-to-page.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/go-to-page/goToAccessSitePage.js
  e2e-tests/cypress/support/go-to-page/goToAppealStatementInfoPage.js
  e2e-tests/cypress/support/go-to-page/goToAppealStatementPage.js
  e2e-tests/cypress/support/go-to-page/goToAppealStatementSubmission.js
  e2e-tests/cypress/support/go-to-page/goToApplicantNamePage.js
  e2e-tests/cypress/support/go-to-page/goToCheckYourAnswersPage.js
  e2e-tests/cypress/support/go-to-page/goToCookiePreferences.js
  e2e-tests/cypress/support/go-to-page/goToCostsPage.js
  e2e-tests/cypress/support/go-to-page/goToDecisionDateExpiredPage.js
  e2e-tests/cypress/support/go-to-page/goToDecisionDatePage.js
  e2e-tests/cypress/support/go-to-page/goToDecisionLetterPage.js
  e2e-tests/cypress/support/go-to-page/goToEnforcementNoticePage.js
  e2e-tests/cypress/support/go-to-page/goToHealthAndSafetyPage.js
  e2e-tests/cypress/support/go-to-page/goToHouseholderPlanningPermissionQuestionPage.js
  e2e-tests/cypress/support/go-to-page/goToHouseholderQuestionOutPage.js
  e2e-tests/cypress/support/go-to-page/goToHouseholderQuestionPage.js
  e2e-tests/cypress/support/go-to-page/goToLandingPage.js
  e2e-tests/cypress/support/go-to-page/goToListedBuildingOutPage.js
  e2e-tests/cypress/support/go-to-page/goToListedBuildingPage.js
  e2e-tests/cypress/support/go-to-page/goToNoDecisionDatePage.js
  e2e-tests/cypress/support/go-to-page/goToOtherSiteOwnerToldPage.js
  e2e-tests/cypress/support/go-to-page/goToPageNotFoundPage.js
  e2e-tests/cypress/support/go-to-page/goToPlanningApplicationNumberPage.js
  e2e-tests/cypress/support/go-to-page/goToPlanningApplicationSubmission.js
  e2e-tests/cypress/support/go-to-page/goToPlanningDepartmentOutPage.js
  e2e-tests/cypress/support/go-to-page/goToPlanningDepartmentPage.js
  e2e-tests/cypress/support/go-to-page/goToSiteAddressPage.js
  e2e-tests/cypress/support/go-to-page/goToSiteSafetyPage.js
  e2e-tests/cypress/support/go-to-page/goToStartAppealPage.js
  e2e-tests/cypress/support/go-to-page/goToSubmissionPage.js
  e2e-tests/cypress/support/go-to-page/goToSupportingDocumentsPage.js
  e2e-tests/cypress/support/go-to-page/goToTaskListPage.js
  e2e-tests/cypress/support/go-to-page/goToWhoAreYouPage.js
  e2e-tests/cypress/support/go-to-page/goToWholeSiteOwnerPage.js
  e2e-tests/cypress/support/go-to-page/goToYourDetailsPage.js
  e2e-tests/cypress/support/index.js
Labels: please-review-me

#644 chore: bump version of preprod for forms-web-app
  releases/preprod/app.yml
Labels: please-review-me

#640 feat(lpa-submissions-e2e-tests): created feature file and step tests …
  lpa-submissions-e2e-tests/cypress.json
  lpa-submissions-e2e-tests/cypress/integration/appealsDevelopmentPlan.feature
  lpa-submissions-e2e-tests/cypress/integration/appealsDevelopmentPlan/appealsDevelopmentPlanSteps.js
  lpa-submissions-e2e-tests/cypress/support/PageObjects/appeals-development-plan-pageobjects.js
  lpa-submissions-e2e-tests/cypress/support/appeals-development-plan/developmentPlanRadioButton.js
  lpa-submissions-e2e-tests/cypress/support/appeals-development-plan/inputDevelopmentPlanDetails.js
  lpa-submissions-e2e-tests/cypress/support/appeals-development-plan/validateDevelopmentPlanErrorMessage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-development-plan/validateDevelopmentPlanPageHeading.js
  lpa-submissions-e2e-tests/cypress/support/appeals-development-plan/validateDevelopmentPlanPageTitle.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToDevelopmentPlanPage.js
  lpa-submissions-e2e-tests/cypress/support/commands.js
  lpa-submissions-e2e-tests/package-lock.json
  lpa-submissions-e2e-tests/package.json
Labels: please-review-me

#647 fix(horizon-householder-appeal-publish): update mapping
  packages/horizon-householder-appeal-publish/handler.js
  packages/horizon-householder-appeal-publish/handler.spec.js
Labels: please-review-me

#652 test: provide easy scripts for sending appeals to horizon via cypress
  e2e-tests/cypress.json
  e2e-tests/cypress/integration/appeal-submission-to-horizon/appeal-submission-to-horizon.js
  e2e-tests/cypress/plugins/queue.js
  e2e-tests/package.json
Labels: please-review-me

#658 feat(lpa-questionnaire-web-app): add view for development page
  packages/lpa-questionnaire-web-app/package-lock.json
  packages/lpa-questionnaire-web-app/package.json
  packages/lpa-questionnaire-web-app/src/controllers/development-plan.js
  packages/lpa-questionnaire-web-app/src/lib/views.js
  packages/lpa-questionnaire-web-app/src/routes/development-plan.js
  packages/lpa-questionnaire-web-app/src/routes/index.js
  packages/lpa-questionnaire-web-app/src/services/task.service.js
  packages/lpa-questionnaire-web-app/src/views/development-plan.njk
  packages/lpa-questionnaire-web-app/tests/unit/controllers/development-plan.test.js
  packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
  packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
Labels: please-review-me

#662 chore(rbac): allow access to the document storage data in dev
  infrastructure/clusters/dev.tfvars
  infrastructure/environments/README.md
  infrastructure/environments/storage.tf
  infrastructure/environments/variables.tf
Labels: please-review-me

#661 test(forms-web-app): feature file and steps for when you can appeal page
  e2e-tests/cypress/integration/common/guidance-pages.js
  e2e-tests/cypress/integration/guidance-page-when-you-can-appeal.feature
  e2e-tests/cypress/integration/guidance-page-when-you-can-appeal/guidance-page-when-you-can-appeal.js
  e2e-tests/cypress/support/commands/guidance-page-commands.js
  e2e-tests/cypress/support/go-to-page/goToPageWhenYouCanAppeal.js
Labels: please-review-me

#655 Feature/as 105 other appellant submission
  e2e-tests/cypress/fixtures/as-102-ac1.json
  e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-not-require-site-access.json
  e2e-tests/cypress/fixtures/expected-appeal-where-an-inspector-does-require-site-access.json
  e2e-tests/cypress/fixtures/expected-appeal-with-certificate-a.json
  e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-informed.json
  e2e-tests/cypress/fixtures/expected-appeal-without-certificate-a-other-owner-not-informed.json
  e2e-tests/cypress/fixtures/ucd-831-ac1.json
  e2e-tests/cypress/integration/appeal-submission-to-horizon-other-appellant-submission-scenarios.feature
  e2e-tests/cypress/integration/appeal-submission-to-horizon/appeal-submission-to-horizon.js
  e2e-tests/cypress/integration/common/appeal-submission-to-horizon.js
  packages/horizon-householder-appeal-publish/handler.js
  packages/horizon-householder-appeal-publish/handler.spec.js
Labels: please-review-me

#672 fix(forms-web-app): allow GA_ID to be set dynamically from env var
  docker-compose.yml
  packages/forms-web-app/webpack.dev.js
  packages/forms-web-app/webpack.prod.js
Labels: please-review-me

#673 fix(horizon-householder-appeal-publish): update mapping value
  packages/horizon-householder-appeal-publish/handler.js
  packages/horizon-householder-appeal-publish/handler.spec.js
Labels: please-review-me

#682 feat(forms-web-app): add after appeal guidance page
  packages/forms-web-app/src/controllers/guidance-pages.js
  packages/forms-web-app/src/lib/views.js
  packages/forms-web-app/src/routes/guidance-pages.js
  packages/forms-web-app/src/views/guidance-pages/after-appeal.njk
  packages/forms-web-app/tests/unit/controllers/guidance-pages.test.js
  packages/forms-web-app/tests/unit/lib/views.test.js
  packages/forms-web-app/tests/unit/routes/guidance-pages.test.js
Labels: please-review-me

#679 fix(forms-web-app): add env appropriate GA_ID value to each page
  packages/forms-web-app/src/lib/client-side/google-analytics.js
  packages/forms-web-app/src/views/includes/head.njk
  packages/forms-web-app/tests/unit/lib/client-side/__snapshots__/google-analytics.test.js.snap
  packages/forms-web-app/tests/unit/lib/client-side/google-analytics.test.js
  packages/forms-web-app/tests/unit/views/includes/__snapshots__/head.njk.test.js.snap
  packages/forms-web-app/webpack.dev.js
  packages/forms-web-app/webpack.prod.js
  releases/dev/app.yml
Labels: please-review-me

#670 fix(forms-web-app): change cookie expiry from 100 to 1 year
  packages/forms-web-app/src/controllers/cookies.js
  packages/forms-web-app/src/lib/client-side/cookie/cookie-jar.js
  packages/forms-web-app/tests/unit/controllers/cookies.test.js
  packages/forms-web-app/tests/unit/lib/client-side/cookie/cookie-jar.test.js
Labels: please-review-me

#690 build(forms-web-app): removes webpack define config - not needed, misleading
  packages/forms-web-app/webpack.dev.js
  packages/forms-web-app/webpack.prod.js
Labels: please-review-me

#669 fix(forms-web-app): do not display cookie banner on certain pages
  e2e-tests/cypress/integration/appeal-submission-creation-of-submission-information-file.feature
  e2e-tests/cypress/integration/appeal-submission-creation-of-submission-information-file/appeal-submission-creation-of-submission-information-file.js
  e2e-tests/cypress/integration/common/cookies.js
  e2e-tests/cypress/integration/cookie-consent-save-preferences.feature
  e2e-tests/cypress/integration/cookies-consent-bar-without-javascript-enabled.feature
  e2e-tests/cypress/support/appeal-submission-information/submission-information-commands.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/common/assertRadioButtonState.js
  e2e-tests/cypress/support/cookies/confirmCookieConsentBannerDoesNotExist.js
  e2e-tests/cypress/support/cookies/cookies-commands.js
  packages/forms-web-app/src/controllers/appellant-submission/submission-information.js
  packages/forms-web-app/src/controllers/cookies.js
  packages/forms-web-app/src/lib/client-side/cookie/cookie-consent.js
  packages/forms-web-app/src/views/includes/cookie-banner.njk
  packages/forms-web-app/tests/unit/controllers/appellant-submission/submission-information.test.js
  packages/forms-web-app/tests/unit/controllers/cookies.test.js
  packages/forms-web-app/tests/unit/lib/client-side/cookie/cookie-consent.test.js
Labels: please-review-me

#696 feat(keyvault): configure k8s to be able to read from pins internal key vault
  README.md
  charts/app/templates/keyVault.yaml
  charts/app/values.yaml
  infrastructure/environments/kubernetes.tf
  releases/dev/app.yml
  releases/preprod/app.yml
Labels: please-review-me

#701 fix: sets GA tag to dev value
  releases/dev/app.yml
Labels: please-review-me

#703 fix(forms-web-app): fix content on when you can appeal page
  packages/forms-web-app/src/views/guidance-pages/when-appeal.njk
Labels: please-review-me

#702 fix(lpa): remove dependency on deprecated req.params fn
  packages/appeals-service-api/src/controllers/local-planning-authorities.js
  packages/appeals-service-api/tests/unit/controllers/local-planning-authorities.test.js
Labels: please-review-me

#712 chore(document-service): remove cronjob and volume claim for document…
  charts/app/templates/documentServiceApi.yaml
Labels: please-review-me

#713 fix(forms-web-app): update page titles
  packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk
  packages/forms-web-app/src/views/appellant-submission/applicant-name.njk
  packages/forms-web-app/src/views/appellant-submission/application-number.njk
  packages/forms-web-app/src/views/appellant-submission/check-answers.njk
  packages/forms-web-app/src/views/appellant-submission/site-access-safety.njk
  packages/forms-web-app/src/views/appellant-submission/site-access.njk
  packages/forms-web-app/src/views/appellant-submission/site-location.njk
  packages/forms-web-app/src/views/appellant-submission/site-ownership-certb.njk
  packages/forms-web-app/src/views/appellant-submission/site-ownership.njk
  packages/forms-web-app/src/views/appellant-submission/submission-information.njk
  packages/forms-web-app/src/views/appellant-submission/submission.njk
  packages/forms-web-app/src/views/appellant-submission/supporting-documents.njk
  packages/forms-web-app/src/views/appellant-submission/task-list.njk
  packages/forms-web-app/src/views/appellant-submission/upload-application.njk
  packages/forms-web-app/src/views/appellant-submission/upload-decision.njk
  packages/forms-web-app/src/views/appellant-submission/who-are-you.njk
  packages/forms-web-app/src/views/appellant-submission/your-details.njk
  packages/forms-web-app/src/views/eligibility/appeal-statement.njk
  packages/forms-web-app/src/views/eligibility/decision-date.njk
  packages/forms-web-app/src/views/eligibility/listed-building.njk
  packages/forms-web-app/src/views/eligibility/listed-out.njk
  packages/forms-web-app/src/views/eligibility/planning-department.njk
Labels: please-review-me

#718 Fix/as 1230 remove third party cookies on root domain
  packages/forms-web-app/src/lib/remove-unwanted-cookies.js
  packages/forms-web-app/tests/unit/lib/remove-unwanted-cookies.test.js
  packages/forms-web-app/tests/unit/mocks.js
Labels: please-review-me

#717 fix(forms-web-app): adds packages/forms-web-app/src/public/javascript…
  .gitignore
  packages/forms-web-app/.gitignore
Labels: please-review-me

#727 fix(forms-web-app): removes verbose cookie logging for AS-1230
  packages/forms-web-app/src/app.js
  packages/forms-web-app/src/lib/remove-unwanted-cookies.js
Labels: please-review-me

#726 docs: adds docs for seeing what tag is deployed in dev
  README.md
Labels: documentation, please-review-me

#738 fix(document-types): add document types into horizon documents
  packages/horizon-add-document/handler.js
  packages/horizon-add-document/handler.spec.js
  packages/horizon-householder-appeal-publish/handler.js
  packages/horizon-householder-appeal-publish/handler.spec.js
Labels: please-review-me

#739 fix(forms-web-app): update page titles
  packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk
  packages/forms-web-app/src/views/appellant-submission/applicant-name.njk
  packages/forms-web-app/src/views/appellant-submission/application-number.njk
  packages/forms-web-app/src/views/appellant-submission/check-answers.njk
  packages/forms-web-app/src/views/appellant-submission/site-access-safety.njk
  packages/forms-web-app/src/views/appellant-submission/site-access.njk
  packages/forms-web-app/src/views/appellant-submission/site-location.njk
  packages/forms-web-app/src/views/appellant-submission/site-ownership-certb.njk
  packages/forms-web-app/src/views/appellant-submission/site-ownership.njk
  packages/forms-web-app/src/views/appellant-submission/submission-information.njk
  packages/forms-web-app/src/views/appellant-submission/submission.njk
  packages/forms-web-app/src/views/appellant-submission/supporting-documents.njk
  packages/forms-web-app/src/views/appellant-submission/task-list.njk
  packages/forms-web-app/src/views/appellant-submission/upload-application.njk
  packages/forms-web-app/src/views/appellant-submission/upload-decision.njk
  packages/forms-web-app/src/views/appellant-submission/who-are-you.njk
  packages/forms-web-app/src/views/appellant-submission/your-details.njk
  packages/forms-web-app/src/views/eligibility/appeal-statement.njk
  packages/forms-web-app/src/views/eligibility/decision-date.njk
  packages/forms-web-app/src/views/eligibility/listed-building.njk
  packages/forms-web-app/src/views/eligibility/listed-out.njk
  packages/forms-web-app/src/views/eligibility/planning-department.njk
Labels: please-review-me

#740 fix(forms-web-app): fix existing session id conflict
  packages/forms-web-app/src/controllers/appellant-submission/submission.js
Labels: please-review-me

#601 docs(main readme): added logging docs to main readme and out of speci…
  README.md
  packages/appeal-reply-service-api/README.md
  packages/document-service-api/README.md
Labels: please-review-me

#745 fix(e2e-tests): allow waiting for GA code to execute so expected cookie is set
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/cookies/confirmHasGoogleAnalyticsCookies.js
  e2e-tests/package-lock.json
  e2e-tests/package.json
Labels: please-review-me

#750 fix(e2e-tests): remove reliance on base URL to avoid local test failures against other envs
  e2e-tests/cypress/integration/cookie-consent-save-preferences/cookie-consent-save-preferences.js
Labels: please-review-me

#746 feat(appeals-api-service): send email via Notify on appeal submission
  README.md
  docker-compose.yml
  packages/appeals-service-api/package-lock.json
  packages/appeals-service-api/package.json
  packages/appeals-service-api/src/lib/config.js
  packages/appeals-service-api/src/lib/notify.js
  packages/appeals-service-api/src/services/appeal.service.js
  packages/appeals-service-api/src/services/lpa.service.js
  packages/appeals-service-api/tests/unit/lib/notify.test.js
  packages/appeals-service-api/tests/unit/services/appeal.service.test.js
Labels: please-review-me

#743 fix(lpa-questionnaire-web-app): fix error link move to text box in de…
  packages/lpa-questionnaire-web-app/src/views/development-plan.njk
Labels: please-review-me

#747 feat(lpa-questionnaire): add view for upload plans
  packages/lpa-questionnaire-web-app/package-lock.json
  packages/lpa-questionnaire-web-app/package.json
  packages/lpa-questionnaire-web-app/src/app.js
  packages/lpa-questionnaire-web-app/src/config.js
  packages/lpa-questionnaire-web-app/src/controllers/upload-plans.js
  packages/lpa-questionnaire-web-app/src/lib/views.js
  packages/lpa-questionnaire-web-app/src/public/stylesheets/main.css
  packages/lpa-questionnaire-web-app/src/routes/index.js
  packages/lpa-questionnaire-web-app/src/routes/upload-plans.js
  packages/lpa-questionnaire-web-app/src/sass/main.scss
  packages/lpa-questionnaire-web-app/src/views/upload-plans.njk
  packages/lpa-questionnaire-web-app/tests/unit/controllers/upload-plans.test.js
  packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
  packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
  packages/lpa-questionnaire-web-app/tests/unit/routes/upload-plans.test.js
Labels: please-review-me

#751 feat: allow appeal submission with system test borough council lpa
  charts/app/templates/lpa.yaml
Labels: please-review-me

#760 test: update cypress fixture file uploads to handle pdf and other files
  e2e-tests/cypress/fixtures/expected-appeal-with-many-documents.json
  e2e-tests/cypress/integration/common/appeal-submission-to-horizon.js
  e2e-tests/cypress/support/appeal-statement-submission/uploadAppealStatementFile.js
  e2e-tests/cypress/support/appellant-submission-decision-letter/uploadDecisionLetterFile.js
  e2e-tests/cypress/support/appellant-submission-supporting-documents/uploadSupportingDocuments.js
  e2e-tests/cypress/support/appellant-submission-upload-application/uploadPlanningApplicationFile.js
Labels: please-review-me

#778 fix(add-document): remove the maxBodyLength limitation
  packages/horizon-add-document/handler.js
  packages/horizon-add-document/handler.spec.js
Labels: bug, please-review-me

#783 fix(prod): update template id [CI SKIP]
  releases/prod/app.yml
Labels: please-review-me, release

#786 chore(prod): re-enable acp version of site
  releases/prod/app.yml
Labels: please-review-me, release

#785 fix(forms-web-app): correct the date format on the decision date drop…
  packages/forms-web-app/src/app.js
  packages/forms-web-app/src/config.js
  packages/forms-web-app/src/views/eligibility/decision-date-passed.njk
  packages/forms-web-app/tests/unit/controllers/eligibility/decision-date.test.js
Labels: please-review-me

#787 Disable ACP in Prod
  releases/prod/app.yml
Labels: please-review-me, release

#791 feat(forms-web-app): added non-js fallback for LPD selection
  packages/forms-web-app/src/views/eligibility/planning-department.njk
Labels: please-review-me

#797 feat(forms-web-app): update implementation of page not found
  e2e-tests/cypress/integration/not-found.feature
  packages/forms-web-app/src/views/error/not-found.njk
Labels: please-review-me

#788 fix(forms-web-app): correct the date format on the decision date drop…
  packages/forms-web-app/src/app.js
  packages/forms-web-app/src/config.js
  packages/forms-web-app/src/views/eligibility/decision-date-passed.njk
  packages/forms-web-app/tests/unit/controllers/eligibility/decision-date.test.js
Labels: please-review-me

#801 Feature/as 986 - LPD selection without JavaScript
  e2e-tests/cypress/integration/common/eligibility-local-planning-department.js
  e2e-tests/cypress/integration/eligibility-local-planning-department-no-js.feature
  e2e-tests/cypress/support/commands/eligibility-commands.js
  e2e-tests/cypress/support/commands/navigation-commands.js
  e2e-tests/cypress/support/eligibility-local-planning-department/confirmEligibleLocalPlanningDepartmentWithoutJs.js
  e2e-tests/cypress/support/eligibility-local-planning-department/confirmPlanningDepartmentSelectedWithoutJs.js
  e2e-tests/cypress/support/eligibility-local-planning-department/selectEligibleLocalPlanningDepartmentWithoutJs.js
  e2e-tests/cypress/support/eligibility-local-planning-department/selectIneligibleLocalPlanningDepartmentWithoutJs.js
  e2e-tests/cypress/support/eligibility-local-planning-department/selectLocalPlanningDepartmentWithoutJs.js
  e2e-tests/cypress/support/go-to-page/goToPlanningDepartmentPageWithoutJs.js
  e2e-tests/cypress/support/visit-without-javascript-enabled.js
  packages/forms-web-app/src/views/eligibility/planning-department.njk
Labels: please-review-me

#781 feat(forms-web-app): display alternative content for /cookies when JS is disabled
  e2e-tests/cypress/integration/cookie-consent-view-preferences-with-javascript-enabled.feature
  e2e-tests/cypress/integration/cookie-consent-view-preferences-with-javascript-enabled/cookie-consent-view-preferences-with-javascript-enabled.js
  e2e-tests/cypress/integration/cookie-consent-view-preferences-without-javascript-enabled.feature
  e2e-tests/cypress/integration/cookie-consent-view-preferences-without-javascript-enabled/cookie-consent-view-preferences-without-javascript-enabled.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/cookie-consent-view-preferences/commands.js
  e2e-tests/cypress/support/cookie-consent-view-preferences/confirmBodyContentWithJavaScriptEnabled.js
  e2e-tests/cypress/support/cookie-consent-view-preferences/confirmBodyContentWithoutJavaScriptEnabled.js
  e2e-tests/cypress/support/cookie-consent-view-preferences/confirmGenericPageContentExists.js
  e2e-tests/cypress/support/cookie-consent-view-preferences/confirmPageHeadingWithJavaScriptEnabled.js
  e2e-tests/cypress/support/cookie-consent-view-preferences/confirmPageHeadingWithoutJavaScriptEnabled.js
  e2e-tests/cypress/support/go-to-page/goToCookiePreferences.js
  e2e-tests/cypress/support/go-to-page/goToHouseholderQuestionPage.js
  e2e-tests/cypress/support/visit-without-javascript-enabled.js
  packages/forms-web-app/src/lib/client-side/cookie-preferences-page.js
  packages/forms-web-app/src/lib/client-side/cookie-preferences/index.js
  packages/forms-web-app/src/public/stylesheets/main.css
  packages/forms-web-app/src/sass/main.scss
  packages/forms-web-app/src/views/cookies.njk
  packages/forms-web-app/src/views/includes/cookies-without-js.njk
  packages/forms-web-app/src/views/includes/head.njk
  packages/forms-web-app/tests/unit/lib/client-side/cookie-preferences-page.test.js
  packages/forms-web-app/tests/unit/lib/client-side/cookie-preferences/index.test.js
  packages/forms-web-app/tests/unit/views/includes/__snapshots__/head.njk.test.js.snap
  packages/forms-web-app/webpack.common.js
Labels: please-review-me

#804 feat(forms-web-app): update start guidance content
  packages/forms-web-app/src/views/guidance-pages/start-appeal.njk
Labels: please-review-me

#793 Add support for multiple alert emails
  .github/workflows/infra-environments.yml
  infrastructure/environments/README.md
  infrastructure/environments/local.tf
  infrastructure/environments/message_queue.tf
  infrastructure/environments/monitoring.tf
  infrastructure/environments/variables.tf
Labels: infrastructure, please-review-me

#806 feat(forms-web-app): the appeal statement is mandatory
  e2e-tests/cypress/integration/appeal-statement-submission.feature
  packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
  packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement-schema.test.js
  packages/forms-web-app/tests/unit/validators/appellant-submission/appeal-statement.test.js
Labels: draft

#827 test(e2e-tests): update mandatory decision letter in feature file and…
  e2e-tests/cypress/integration/appellant-submission-decision-letter.feature
  e2e-tests/cypress/integration/appellant-submission-decision-letter/appellant-submission-decision-letter.js
Labels: please-review-me

#832 feat(forms-web-app): update page title for error state
  e2e-tests/cypress/integration/common/eligibility-householder.js
  e2e-tests/package-lock.json
  packages/forms-web-app/src/views/eligibility/householder-planning-permission.njk
Labels: please-review-me

#835 feat(forms-web-app): update page tile for error state
  e2e-tests/cypress/integration/common/eligibility-householder.js
  e2e-tests/package-lock.json
  packages/forms-web-app/src/views/eligibility/householder-planning-permission.njk
Labels: please-review-me

#813 feat(document-service-api): updated openapi documentation
  packages/document-service-api/src/api/openapi.yaml
Labels: please-review-me

#839 fix(forms-web-app): change heading from non JS page to match heading …
  e2e-tests/cypress/support/cookie-consent-view-preferences/confirmPageHeadingWithoutJavaScriptEnabled.js
  packages/forms-web-app/src/views/cookies.njk
Labels: please-review-me

#869 fix(forms-web-app): remove gray colour from bottom of generated appeal PDF
  packages/forms-web-app/src/views/appellant-submission/submission-information.njk
Labels: please-review-me

#865 fix(forms-web-app): adds 'error' to page title - listed building
  e2e-tests/cypress/integration/eligibility-listed-building-status.feature
  e2e-tests/cypress/support/eligibility-listed-building-status/confirmListedBuildingStatementIsRequired.js
  packages/forms-web-app/src/views/eligibility/listed-building.njk
Labels: please-review-me

#890 chore(release): prod release
  releases/prod/app.yml
Labels: please-review-me, release

#867 chore(pentest): remove pen test access in prod
  infrastructure/clusters/prod.tfvars
Labels: infrastructure, please-review-me
