Repository Planning-Inspectorate/appeal-planning-decision, pull requests merged in 2021-01, with the labels that each got.

#294 Feature/ucd 1194 update links
  e2e-tests/cypress/integration/appellant-submission-footer-links.feature
  e2e-tests/cypress/integration/common/appellant-submission-footer-links.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToAccessSitePage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToAppealStatementSubmission.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToApplicantNamePage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToCheckYourAnswersPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToDecisionLetterPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToHealthAndSafetyPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToOtherAppealsPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToOtherSiteOwnerToldPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToPlanningApplicationNumberPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToPlanningApplicationSubmission.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSiteAddressPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSubmissionPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSupportingDocumentsPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToTaskListPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToWhoAreYouPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToWholeSiteOwnerPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToYourDetailsPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToAppealStatementInfoPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToDecisionDateExpiredPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToDecisionDatePage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToListedBuildingOutPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToListedBuildingPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToNoDecisionDatePage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToPlanningDepartmentOutPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToPlanningDepartmentPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToStartAppealPage.js
  e2e-tests/cypress/support/appeal-submission-tasklist/goToTaskListPage.js
  e2e-tests/cypress/support/appellant-submission-footer-links/confirmPrivacyLinkDisplayed.js
  e2e-tests/cypress/support/appellant-submission-footer-links/confirmTermsAndConditionsLinkDisplayed.js
  e2e-tests/cypress/support/commands.js
  forms-web-app/src/views/layouts/main.njk
Labels: please-review-me

#301 docs(readme): add information on debugging releases and writing good commit messages
  README.md
Labels: please-review-me

#303 chore: reset the app versions to 1.0.0
  clusters/dev/app.yml
  clusters/preprod/app.yml
Labels: please-review-me

#305 chore: create prod environment
  .github/workflows/infra-environments.yml
  infrastructure/clusters/prod.tfvars
Labels: please-review-me, release

#314 fix(start): update the npm start scripts to target correct file
  packages/appeals-service-api/package.json
  packages/common/package.json
  packages/document-service-api/package.json
  packages/forms-web-app/package.json
Labels: please-review-me

#313 feat(forms-web-app): site access details is limited to 255 characters
  packages/forms-web-app/src/validators/appellant-submission/site-access.js
  packages/forms-web-app/tests/unit/validators/appellant-submission/site-access.test.js
Labels: please-review-me

#298 feat(ingress): configure ingress redirects
  charts/app/templates/ingress.yaml
  charts/app/values.yaml
Labels: please-review-me

#315 feat(forms-web-app): Google Analytics feature
  e2e-tests/cypress/integration/common/appeal-header-footer.js
  e2e-tests/cypress/integration/google-analytics.feature
  e2e-tests/cypress/support/appeal-header-footer-links/confirmGoogleAnalyticsLinkIsPresent.js
  e2e-tests/cypress/support/commands.js
  packages/forms-web-app/src/app.js
  packages/forms-web-app/src/config.js
  packages/forms-web-app/src/views/includes/head.njk
Labels: please-review-me

#328 test(e2e-tests): feature file and steps for ACP integration
  e2e-tests/README.md
  e2e-tests/cypress/integration-with-acp/eligibility-check-decision-date.feature
  e2e-tests/cypress/integration-with-acp/handle-unavailable-routes.feature
  e2e-tests/cypress/integration/common/integration-with-acp.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationApplicantNamePage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationTaskListPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationWhoAreYouPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/appellant-submission/confirmNavigationYourDetailsPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDateExpiredPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDatePage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationNoDecisionDatePage.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/integration-with-acp/confirmNavigationAcpPage.js
  e2e-tests/cypress/support/integration-with-acp/confirmNavigationPageNotFoundPage.js
  e2e-tests/cypress/support/integration-with-acp/goToPageNotFoundPage.js
Labels: please-review-me

#331 chore(coverage): update jest config to achieve 100 coverage
  packages/forms-web-app/jest.config.js
  packages/forms-web-app/src/controllers/appellant-submission/upload-application.js
  packages/forms-web-app/src/controllers/appellant-submission/upload-decision.js
  packages/forms-web-app/src/controllers/eligibility/decision-date.js
  packages/forms-web-app/src/lib/appeals-api-wrapper.js
  packages/forms-web-app/src/lib/session.js
  packages/forms-web-app/src/validators/appellant-submission/your-details.js
  packages/forms-web-app/src/validators/eligibility/decision-date.js
Labels: please-review-me

#321 test: new scenario added for restricted access information field max …
  e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site.feature
  e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site/appeal-submission-access-to-appeal-site.js
Labels: please-review-me

#332 build: added npm scripts for ACP tests
  e2e-tests/package.json
  package.json
Labels: please-review-me

#336 test(e2e-tests): update tests and docs for ACP integration
  README.md
  docker-compose.yml
  e2e-tests/cypress/integration-with-acp/eligibility-check-decision-date.feature
  e2e-tests/cypress/integration-with-acp/handle-unavailable-routes.feature
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToAccessSitePage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToAppealStatementSubmission.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToApplicantNamePage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToCheckYourAnswersPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToDecisionLetterPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToHealthAndSafetyPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToPlanningApplicationNumberPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToPlanningApplicationSubmission.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSiteAddressPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSubmissionPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToTaskListPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToWhoAreYouPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToWholeSiteOwnerPage.js
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToYourDetailsPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToAppealStatementInfoPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToListedBuildingOutPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToListedBuildingPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToPlanningDepartmentOutPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToPlanningDepartmentPage.js
Labels: please-review-me

#335 fix(forms-web-app): move submission and confirmation routes into appe…
  e2e-tests/cypress/support/appeal-navigation/appellant-submission/goToSubmissionPage.js
  e2e-tests/cypress/support/appellant-confirms-declaration/agreeToTheDeclaration.js
  e2e-tests/cypress/support/appellant-confirms-declaration/confirmAppealNotSubmitted.js
  e2e-tests/cypress/support/appellant-confirms-declaration/confirmAppealSubmitted.js
  e2e-tests/cypress/support/appellant-confirms-declaration/doNotAgreeToTheDeclaration.js
  e2e-tests/cypress/support/appellant-submission-check-your-answers/confirmSubmissionPage.js
  packages/forms-web-app/src/controllers/appellant-submission/confirmation.js
  packages/forms-web-app/src/controllers/appellant-submission/submission.js
  packages/forms-web-app/src/lib/views.js
  packages/forms-web-app/src/routes/appellant-submission/confirmation.js
  packages/forms-web-app/src/routes/appellant-submission/index.js
  packages/forms-web-app/src/routes/appellant-submission/submission.js
  packages/forms-web-app/src/routes/confirmation.js
  packages/forms-web-app/src/routes/index.js
  packages/forms-web-app/src/routes/submission.js
  packages/forms-web-app/src/validators/appellant-submission/submission.js
  packages/forms-web-app/src/views/appellant-submission/confirmation.njk
  packages/forms-web-app/src/views/appellant-submission/submission.njk
  packages/forms-web-app/src/views/check-answers.njk
  packages/forms-web-app/tests/unit/controllers/appellant-submission/confirmation.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/submission.test.js
  packages/forms-web-app/tests/unit/lib/views.test.js
  packages/forms-web-app/tests/unit/routes/appellant-submission/confirmation.test.js
  packages/forms-web-app/tests/unit/routes/appellant-submission/index.test.js
  packages/forms-web-app/tests/unit/routes/appellant-submission/submission.test.js
  packages/forms-web-app/tests/unit/routes/confirmation.test.js
  packages/forms-web-app/tests/unit/routes/index.test.js
  packages/forms-web-app/tests/unit/routes/submission.test.js
  packages/forms-web-app/tests/unit/validators/appellant-submission/submission.test.js
Labels: please-review-me

#339 Fix/cypress with http basic
  e2e-tests/README.md
Labels: please-review-me

#343 ci: update CI pipeline to run tests for both modes i.e ACP and non-ACP
  .github/workflows/e2e-tests-on-PR.yml
  .github/workflows/publish-cucumber-on-merge.yml
  docker-compose.yml
  e2e-tests/cypress/reports/acp/.gitkeep
  e2e-tests/cypress/reports/index.html
  e2e-tests/cypress/reports/pins/.gitkeep
  e2e-tests/package.json
  package.json
Labels: please-review-me

#347 test(e2e-tests): update section status icon feature file
  e2e-tests/cypress/integration/appeal-submission-tasklist.feature
  packages/forms-web-app/src/services/task.service.js
Labels: please-review-me

#352 fix(security): update rbac role to provide readonly to jobs/deployments
  infrastructure/k8s/rbac/user.yaml
Labels: please-review-me, ready-for-new-branching

#360 test(e2e-tests): confirm that no answer is selected by default in the checkbox
  e2e-tests/cypress/integration/appeal-submission-appeal-site-ownership/appeal-submission-appeal-site-ownership.js
Labels: please-review-me

#359 feat(forms-web-app): remove save and return link
  packages/forms-web-app/src/views/appellant-submission/task-list.njk
  packages/forms-web-app/src/views/appellant-submission/your-details.njk
Labels: please-review-me

#354 feat(forms-web-app): add automated tests to validate a file upload ex…
  e2e-tests/cypress/support/appeal-statement-submission/confirmAppealStatementFileIsUploaded.js
  e2e-tests/cypress/support/appellant-submission-decision-letter/confirmDecisionLetterAccepted.js
  e2e-tests/cypress/support/appellant-submission-upload-application/confirmPlanningApplicationAccepted.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/file-upload/validateIndividualFileUpload.js
  packages/forms-web-app/src/controllers/appellant-submission/appeal-statement.js
  packages/forms-web-app/src/controllers/appellant-submission/supporting-documents.js
  packages/forms-web-app/src/controllers/appellant-submission/upload-application.js
  packages/forms-web-app/src/controllers/appellant-submission/upload-decision.js
  packages/forms-web-app/src/lib/documents-api-wrapper.js
  packages/forms-web-app/src/routes/appellant-submission/supporting-documents.js
  packages/forms-web-app/src/validators/appellant-submission/supporting-documents.js
  packages/forms-web-app/src/views/appellant-submission/appeal-statement.njk
  packages/forms-web-app/src/views/appellant-submission/supporting-documents.njk
  packages/forms-web-app/src/views/appellant-submission/upload-application.njk
  packages/forms-web-app/src/views/appellant-submission/upload-decision.njk
  packages/forms-web-app/src/views/components/multi-file-upload/README.md
  packages/forms-web-app/src/views/components/multi-file-upload/macro.njk
  packages/forms-web-app/src/views/components/multi-file-upload/template.njk
  packages/forms-web-app/tests/unit/controllers/appellant-submission/site-access-safety.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/supporting-documents.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/who-are-you.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/your-details.test.js
  packages/forms-web-app/tests/unit/lib/documents-api-wrapper.test.js
  packages/forms-web-app/tests/unit/routes/appellant-submission/supporting-documents.test.js
Labels: please-review-me

#358 chore(branching): use master branch as location of helm charts
  clusters/dev/app.yml
  clusters/preprod/app.yml
Labels: ready-for-new-branching

#371 fix(security): enable port forward in rbac settings
  infrastructure/k8s/rbac/user.yaml
Labels: please-review-me

#344 feat(forms-web-app): extends the appeal for save and navigation feature
  packages/forms-web-app/src/controllers/appellant-submission/appeal-statement.js
  packages/forms-web-app/src/controllers/appellant-submission/applicant-name.js
  packages/forms-web-app/src/controllers/appellant-submission/application-number.js
  packages/forms-web-app/src/controllers/appellant-submission/site-access-safety.js
  packages/forms-web-app/src/controllers/appellant-submission/site-access.js
  packages/forms-web-app/src/controllers/appellant-submission/site-location.js
  packages/forms-web-app/src/controllers/appellant-submission/site-ownership-certb.js
  packages/forms-web-app/src/controllers/appellant-submission/site-ownership.js
  packages/forms-web-app/src/controllers/appellant-submission/supporting-documents.js
  packages/forms-web-app/src/controllers/appellant-submission/upload-application.js
  packages/forms-web-app/src/controllers/appellant-submission/upload-decision.js
  packages/forms-web-app/src/controllers/appellant-submission/your-details.js
  packages/forms-web-app/src/lib/empty-appeal.js
  packages/forms-web-app/src/services/task.service.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/appeal-statement.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/applicant-name.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/application-number.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/site-access-safety.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/site-access.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/site-location.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/site-ownership-certb.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/site-ownership.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/supporting-documents.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-application.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/upload-decision.test.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/your-details.test.js
  packages/forms-web-app/tests/unit/services/task.service.test.js
Labels: please-review-me

#370 test(e2e-tests): confirm that no answer is selected by default in sit…
  e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site.feature
  e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site/appeal-submission-access-to-appeal-site.js
  e2e-tests/cypress/integration/appeal-submission-site-health-and-safety-issues.feature
Labels: please-review-me

#384 feat(forms-web-app): update task list sections name
  packages/forms-web-app/src/controllers/appellant-submission/task-list.js
  packages/forms-web-app/tests/unit/controllers/appellant-submission/task-list.test.js
Labels: please-review-me

#383 test(e2e-tests): add section status e2e tests for appeal site
  e2e-tests/cypress/integration/appeal-submission-access-to-appeal-site.feature
  e2e-tests/cypress/integration/appeal-submission-appeal-site-address.feature
  e2e-tests/cypress/integration/appeal-submission-appeal-site-ownership.feature
  e2e-tests/cypress/integration/appeal-submission-site-health-and-safety-issues.feature
  e2e-tests/cypress/integration/common/appellant-submission-about-the-appeal-site.js
  e2e-tests/cypress/integration/common/appellant-submission-your-details.js
Labels: please-review-me

#392 Subtask/ucd 1538 add ga env variable
  charts/app/templates/formsWebApp.yaml
  charts/app/values.yaml
  e2e-tests/cypress/integration/google-analytics.feature
  e2e-tests/cypress/support/appeal-header-footer/confirmGoogleAnalyticsLinkIsPresent.js
  packages/forms-web-app/src/config.js
  packages/forms-web-app/src/views/includes/head.njk
Labels: please-review-me

#398 test(e2e-tests): adds FF for check your answers
  e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature
Labels: please-review-me

#402 feat(forms-web-app): update LPD eligibility tests to be dynamic
  docker-compose.yml
  e2e-tests/cypress/integration/common/eligibility-local-planning-department.js
  e2e-tests/cypress/integration/eligibility-decision-date-page-components.feature
  e2e-tests/cypress/integration/eligibility-local-planning-department.feature
  e2e-tests/cypress/integration/eligibility-local-planning-department/eligibility-local-planning-department.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationListedBuildingPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationLocalPlanningDepartmentPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmTextOnPage.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/eligibility-local-planning-department/confirmEligibleLocalPlanningDepartment.js
  e2e-tests/cypress/support/eligibility-local-planning-department/confirmIneligibleLocalPlanningDepartment.js
  e2e-tests/cypress/support/eligibility-local-planning-department/provideEligibleLocalPlanningDepartment.js
  e2e-tests/cypress/support/eligibility-local-planning-department/provideIneligibleLocalPlanningDepartment.js
  packages/appeals-service-api/data/lpa-trialists.json
  packages/forms-web-app/src/controllers/eligibility/planning-department.js
  packages/forms-web-app/src/services/department.service.js
  packages/forms-web-app/src/views/eligibility/planning-department-out.njk
  packages/forms-web-app/src/views/eligibility/planning-department.njk
  packages/forms-web-app/tests/unit/controllers/eligibility/planning-department.test.js
Labels: please-review-me

#410 feat(forms-web-app): ensure LPD data is always refreshed
  packages/forms-web-app/src/controllers/eligibility/planning-department.js
  packages/forms-web-app/src/services/department.service.js
  packages/forms-web-app/tests/unit/controllers/eligibility/planning-department.test.js
  packages/forms-web-app/tests/unit/services/department.service.test.js
Labels: please-review-me

#423 feat(forms-web-app): removed inline style to comply with CSP
  charts/app/templates/lpa.yaml
  packages/forms-web-app/src/views/eligibility/planning-department.njk
Labels: please-review-me

#430 test: added placeholder step defs
  e2e-tests/cypress/integration/appellant-submission-check-your-answers.feature
  e2e-tests/cypress/integration/common/appellant-submission-check-your-answers.js
Labels: please-review-me
