Repository Planning-Inspectorate/appeal-planning-decision, pull requests merged in 2021-02, with the labels that each got.

#447 chore: promote versions to preprod for demo
  clusters/preprod/app.yml
Labels: please-review-me

#454 test(e2e-tests): updated FF for Decision Date eligibility check
  e2e-tests/cypress/integration/eligibility-decision-date.feature
Labels: please-review-me

#456 test: update step defs for Decision Date feature
  e2e-tests/cypress/integration-with-acp/handle-unavailable-routes.feature
  e2e-tests/cypress/integration/eligibility-decision-date/eligibility-decision-date.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDateAbsentPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationDecisionDateExpiredPage.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/eligibility-decision-date/accessConfirmHavingNoDecisionDate.js
  e2e-tests/cypress/support/eligibility-decision-date/confirmProvidedDecisionDateWasInvalid.js
Labels: please-review-me

#450 test: test cases for Feature AS-1 added
  .github/workflows/e2e-tests-on-PR.yml
  lpa-submissions-e2e-tests/cypress.json
  lpa-submissions-e2e-tests/cypress/integration/appealsQuestionnaireTaskList.feature
  lpa-submissions-e2e-tests/cypress/integration/appealsQuestionnaireTaskList/appealsQuestionnaireTaskListSteps.js
  lpa-submissions-e2e-tests/cypress/integration/lpa-submission-tasklist/lpa-submission-tasklist.js
  lpa-submissions-e2e-tests/cypress/plugins/index.js
  lpa-submissions-e2e-tests/cypress/reports/index.html
  lpa-submissions-e2e-tests/cypress/reports/lpa/.gitkeep
  lpa-submissions-e2e-tests/cypress/support/PageObjects/appeals-questionnaire-tasklist-pageobjects.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/checkYourAnswers.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToDevelopmentPlanDocumentOrNeighbourhoodPlanPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToExtraConditionsPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToNotifyingInterestedPartiesOfTheAppealPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToOtherRelevantPoliciesPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToPlanningHistoryPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToRepresentationsFromInterestedPartiesPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToReviewAccuracyOfTheAppellantsSubmissionPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToSiteNoticesPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToStatutoryDevelopmentPlanPolicyPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToSupplementaryPlanningDocumentsExtractPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToTellUsAboutAppealSitePage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToTellUsAboutAppealsInImmediateAreaPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToTellingInterestedPartiesAboutTheApplicationPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToUploadPlanningOfficersReportPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/goToUploadThePlansUsedToReachDecisionPage.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/verifyCannotStartStatus.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-navigation/verifyNotStartedStatus.js
  lpa-submissions-e2e-tests/cypress/support/appeals-questionnaire-tasklist/goToAppealsQuestionnaireTasklistPage.js
  lpa-submissions-e2e-tests/cypress/support/commands.js
  lpa-submissions-e2e-tests/cypress/support/index.js
  lpa-submissions-e2e-tests/cypress/support/lpa-submission-tasklist/visitTaskListQuestionnaireSubmissionPage.js
  lpa-submissions-e2e-tests/package-lock.json
  lpa-submissions-e2e-tests/package.json
Labels: please-review-me

#337 chore: remove http basic auth from prod cluster
  clusters/prod/app.yml
Labels: draft, release

#472 test(e2e-tests): add step defs for Costs eligibility check feature
  e2e-tests/cypress/integration/common/eligibility-costs.js
  e2e-tests/cypress/integration/eligibility-costs.feature
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationCostsOutPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationCostsPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationYourAppealStatementPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToCostsPage.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/eligibility-costs/confirmAcpLinkDisplayed.js
  e2e-tests/cypress/support/eligibility-costs/confirmGuidanceLinkDisplayed.js
  e2e-tests/cypress/support/eligibility-costs/provideCostsAnswerNo.js
  e2e-tests/cypress/support/eligibility-costs/provideCostsAnswerYes.js
Labels: please-review-me

#477 fix(nginx-ingress): restart the pods after deployment to pick up configmap changes
  infrastructure/k8s/setup.sh
Labels: please-review-me

#490 test(e2e-tests): added step defs for Householder Question feature
  e2e-tests/cypress/integration/common/eligibility-householder.js
  e2e-tests/cypress/integration/eligibility-appeal-householder-planning-permission.feature
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationHouseholderQuestionOutPage.js
  e2e-tests/cypress/support/appeal-navigation-confirmation/eligibility/confirmNavigationHouseholderQuestionPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToHouseholderQuestionOutPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToHouseholderQuestionPage.js
  e2e-tests/cypress/support/appeal-navigation/eligibility/goToLandingPage.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/eligibility-householder/accessDetails.js
  e2e-tests/cypress/support/eligibility-householder/confirmDetailsDisplayed.js
  e2e-tests/cypress/support/eligibility-householder/provideHouseholderAnswerNo.js
  e2e-tests/cypress/support/eligibility-householder/provideHouseholderAnswerYes.js
Labels: please-review-me

#494 fix(forms-web-app): updated step defs
  e2e-tests/cypress/integration/common/eligibility-householder.js
  e2e-tests/cypress/integration/eligibility-appeal-householder-planning-permission/eligibility-appeal-householder-planning-permission.js
  packages/forms-web-app/src/views/eligibility/householder-planning-permission.njk
Labels: please-review-me

#499 fix(appeal-data-panel): data would not update when id changed
  packages/lpa-questionnaire-web-app/src/middleware/fetch-appeal.js
  packages/lpa-questionnaire-web-app/tests/unit/middleware/fetch-appeal.test.js
Labels: please-review-me

#508 chore(eslintrc): update eslint to es2020
  packages/lpa-questionnaire-web-app/.eslintrc
Labels: please-review-me

#506 Subtask/ucd 1691 ff for horizon queue
  e2e-tests/cypress/integration/appeal-submission-to-horizon.feature
Labels: please-review-me

#511 Subtask/as 81 task completion logic
  packages/lpa-questionnaire-web-app/src/services/task-status/other-appeals.js
  packages/lpa-questionnaire-web-app/src/services/task.service.js
  packages/lpa-questionnaire-web-app/tests/unit/services/task-status/other-appeals.test.js
Labels: please-review-me

#512 feat(lpa-questionnaire): add backlink to session for back button usage
  packages/lpa-questionnaire-web-app/src/controllers/other-appeals.js
  packages/lpa-questionnaire-web-app/src/controllers/placeholder.js
  packages/lpa-questionnaire-web-app/src/controllers/task-list.js
  packages/lpa-questionnaire-web-app/src/views/placeholder.njk
  packages/lpa-questionnaire-web-app/tests/unit/controllers/other-appeals.test.js
  packages/lpa-questionnaire-web-app/tests/unit/controllers/placeholder.test.js
  packages/lpa-questionnaire-web-app/tests/unit/controllers/task-list.test.js
Labels: please-review-me

#525 chore: change PR template from UCD to AS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: please-review-me

#524 feat(appeals-service-api): add appeal to publisher queue on submit
  charts/app/templates/appealsServiceApi.yaml
  charts/app/values.yaml
  docker-compose.yml
  packages/appeals-service-api/api/openapi.yaml
  packages/appeals-service-api/package-lock.json
  packages/appeals-service-api/package.json
  packages/appeals-service-api/src/controllers/appeals.js
  packages/appeals-service-api/src/lib/config.js
  packages/appeals-service-api/src/lib/queue.js
  packages/appeals-service-api/src/services/validation.service.js
  packages/appeals-service-api/tests/integration/appeals.test.js
  packages/appeals-service-api/tests/unit/services/validation.service.test.js
Labels: please-review-me

#532 Subtask/ucd 831 refactor controllers
  packages/appeals-service-api/api/openapi.yaml
  packages/appeals-service-api/src/controllers/appeals.js
  packages/appeals-service-api/src/error/apiError.js
  packages/appeals-service-api/src/lib/parse-date-string.js
  packages/appeals-service-api/src/routes/appeals.js
  packages/appeals-service-api/src/services/appeal.service.js
  packages/appeals-service-api/src/validators/appeals/appeals.validator.js
  packages/appeals-service-api/tests/integration/appeals.test.js
  packages/appeals-service-api/tests/unit/controllers/appeals.test.js
  packages/appeals-service-api/tests/unit/routes/appeals/appeals.test.js
  packages/appeals-service-api/tests/unit/services/appeal.service.test.js
Labels: please-review-me

#544 chore(appeals-reply-service): add reply service url to lpq questionnaire config
  charts/app/templates/lpaQuestionnaireWebApp.yaml
  charts/app/values.yaml
Labels: please-review-me

#550 fix(infrastructure): change default vpn sku to VpnGw1AZ
  infrastructure/environments/README.md
  infrastructure/environments/variables.tf
Labels: please-review-me

#375 chore(dev): configure openfaas infrastructure and horizon functions
  clusters/dev/app.yml
  clusters/dev/functions.yml
  clusters/dev/openfaas.yml
Labels: please-review-me

#530 test(submission-accuracy): feature file for accuracy of apellants sub…
  lpa-submissions-e2e-tests/cypress/integration/accuracyAppellantsSubmission.feature
Labels: please-review-me

#558 Subtask/as 1200 pdf helm
  charts/app/templates/gotenberg.yaml
  charts/app/templates/pdfServiceApi.yaml
  charts/app/templates/service.yaml
  charts/app/values.yaml
  releases/dev/app.yml
Labels: please-review-me

#568 docs(forms-web-app): adds docblock for initial-cookies middleware
  packages/forms-web-app/src/middleware/initial-cookies.js
Labels: documentation, please-review-me

#567 feat(pdf-service-api): New service to generate pdf files
  packages/appeals-service-api/README.md
  packages/pdf-service-api/api/openapi.yaml
  packages/pdf-service-api/mocks/mocks.js
  packages/pdf-service-api/src/__tests__/pdf-failure.spec.js
  packages/pdf-service-api/src/__tests__/pdf-success.spec.js
  packages/pdf-service-api/src/__tests__/pdf.spec.js
  packages/pdf-service-api/src/controllers/pdf.js
  packages/pdf-service-api/src/lib/pdfUtils.js
Labels: please-review-me

#570 feat(e2e-tests): adds FF for cookie consent bar
  e2e-tests/cypress/integration/cookies-consent-bar.feature
Labels: please-review-me

#574 Subtask/as 1030 submission accuracy validation
  packages/lpa-questionnaire-web-app/src/controllers/accuracy-submission.js
  packages/lpa-questionnaire-web-app/src/routes/accuracy-submission.js
  packages/lpa-questionnaire-web-app/src/validators/accuracy-submission.js
  packages/lpa-questionnaire-web-app/tests/unit/controllers/submission-accuracy.test.js
  packages/lpa-questionnaire-web-app/tests/unit/validators/accuracy-submission.test.js
Labels: please-review-me

#556 feat(lpa-questionnaire-web-app): initial commit new view not yet buil…
  lpa-submissions-e2e-tests/package-lock.json
  lpa-submissions-e2e-tests/package.json
  packages/lpa-questionnaire-web-app/src/controllers/extra-conditions.js
  packages/lpa-questionnaire-web-app/src/lib/views.js
  packages/lpa-questionnaire-web-app/src/routes/extra-conditions.js
  packages/lpa-questionnaire-web-app/src/routes/index.js
  packages/lpa-questionnaire-web-app/src/services/task.service.js
  packages/lpa-questionnaire-web-app/src/views/extra-conditions.njk
  packages/lpa-questionnaire-web-app/tests/unit/controllers/extra-conditions.test.js
  packages/lpa-questionnaire-web-app/tests/unit/lib/views.test.js
  packages/lpa-questionnaire-web-app/tests/unit/routes/index.test.js
Labels: please-review-me

#582 chore(lpa-questionnaire): bump version on preprod
  releases/preprod/app.yml
Labels: please-review-me

#591 feat(lpa-questionnaire): extra conditions validator added
  packages/lpa-questionnaire-web-app/src/routes/extra-conditions.js
  packages/lpa-questionnaire-web-app/src/validators/extra-conditions.js
  packages/lpa-questionnaire-web-app/tests/unit/validators/extra-conditions.test.js
Labels: please-review-me

#598 fix(appeal-header): fix homepage link in layout header
  e2e-tests/cypress/integration/common/appeal-header-footer.js
  e2e-tests/cypress/support/appeal-header-footer/confirmHomepageLinkIsDisplayed.js
  e2e-tests/cypress/support/commands.js
  packages/forms-web-app/src/views/layouts/main-no-back-button.njk
  packages/forms-web-app/src/views/layouts/main.njk
Labels: please-review-me
