Repository Planning-Inspectorate/appeal-planning-decision, pull requests merged in 2021-11, with the labels that each got.

#1838 feat(as-3574): azure functions for data transfer
  packages/horizon-functions/horizon-householder-appeal-publish/index.js
  packages/horizon-functions/horizon-householder-appeal-publish/src/config.js
  packages/horizon-functions/horizon-householder-appeal-publish/src/transmitAppealData.js
  packages/horizon-functions/package-lock.json
  packages/horizon-functions/package.json
  packages/horizon-functions/sql-householder-appeal-publish/.eslintignore
  packages/horizon-functions/sql-householder-appeal-publish/.eslintrc
  packages/horizon-functions/sql-householder-appeal-publish/.funcignore
  packages/horizon-functions/sql-householder-appeal-publish/.npmrc
  packages/horizon-functions/sql-householder-appeal-publish/.prettierrc
  packages/horizon-functions/sql-householder-appeal-publish/CHANGELOG.md
  packages/horizon-functions/sql-householder-appeal-publish/__setups__/date.js
  packages/horizon-functions/sql-householder-appeal-publish/function.json
  packages/horizon-functions/sql-householder-appeal-publish/handler-reply.js
  packages/horizon-functions/sql-householder-appeal-publish/host.json
  packages/horizon-functions/sql-householder-appeal-publish/index.js
  packages/horizon-functions/sql-householder-appeal-publish/src/callHorizon.js
  packages/horizon-functions/sql-householder-appeal-publish/src/catchErrorHandling.js
  packages/horizon-functions/sql-householder-appeal-publish/src/config.js
  packages/horizon-functions/sql-householder-appeal-publish/src/convertToSoapKVPair.js
  packages/horizon-functions/sql-householder-appeal-publish/src/createContacts.js
  packages/horizon-functions/sql-householder-appeal-publish/src/getHorizonId.js
  packages/horizon-functions/sql-householder-appeal-publish/src/getLpaData.js
  packages/horizon-functions/sql-householder-appeal-publish/src/lib/logger.js
  packages/horizon-functions/sql-householder-appeal-publish/src/lib/rabbitmq.js
  packages/horizon-functions/sql-householder-appeal-publish/src/logic/addDocument.js
  packages/horizon-functions/sql-householder-appeal-publish/src/logic/createContact.js
  packages/horizon-functions/sql-householder-appeal-publish/src/logic/documentTypes.js
  packages/horizon-functions/sql-householder-appeal-publish/src/publishDocuments.js
  packages/horizon-functions/sql-householder-appeal-publish/src/sectionTypes.js
  packages/horizon-functions/sql-householder-appeal-publish/tests/getHorizonId.spec.js
  packages/horizon-functions/sql-householder-appeal-publish/tests/handler-reply-mocked.spec.js
  packages/horizon-functions/sql-householder-appeal-publish/tests/handler-reply.spec.js
  packages/horizon-functions/sql-householder-appeal-publish/tests/handler.spec.js
  packages/horizon-functions/sql-householder-appeal-publish/tests/mockAppealReply.js
  packages/horizon-functions/sql-householder-lpa-publish/function.json
  packages/horizon-functions/sql-householder-lpa-publish/handler-reply.js
  packages/horizon-functions/sql-householder-lpa-publish/index.js
  packages/horizon-functions/sql-householder-lpa-publish/src/callHorizon.js
  packages/horizon-functions/sql-householder-lpa-publish/src/config.js
  packages/horizon-functions/sql-householder-lpa-publish/src/convertToSoapKVPair.js
  packages/horizon-functions/sql-householder-lpa-publish/src/createContacts.js
  packages/horizon-functions/sql-householder-lpa-publish/src/getHorizonId.js
  packages/horizon-functions/sql-householder-lpa-publish/src/getLpaData.js
  packages/horizon-functions/sql-householder-lpa-publish/src/logic/addDocument.js
  packages/horizon-functions/sql-householder-lpa-publish/src/logic/createContact.js
  packages/horizon-functions/sql-householder-lpa-publish/src/logic/documentTypes.js
  packages/horizon-functions/sql-householder-lpa-publish/src/publishDocuments.js
  packages/horizon-functions/sql-householder-lpa-publish/src/sectionTypes.js
Labels: draft

#1840 feat(cosmodb to blobstorage): migration response covers failed item info
  packages/document-service-api/src/lib/migrateMetadata.js
  packages/document-service-api/src/lib/migrateMetadata.test.js
Labels: please-review-me

#1867 fix(as-58): removed conflict remarks added to package-lock.json in pr…
  packages/lpa-questionnaire-web-app/package-lock.json
Labels: please-review-me

#1873 feat(as-3873): rename test folder to __test__
  packages/magiclink-auth-service-api/__tests__/integration/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/resources/magicLinkData.json
  packages/magiclink-auth-service-api/__tests__/setup-jest.js
  packages/magiclink-auth-service-api/__tests__/unit/controllers/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/error/apiErrorHandler.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/createAuthToken.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/createMagicLink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/sendMagicLinkEmail.test.js
  packages/magiclink-auth-service-api/__tests__/unit/lib/getYamlAsJson.test.js
  packages/magiclink-auth-service-api/__tests__/unit/mapper/magicLinkTokenMapper.test.js
  packages/magiclink-auth-service-api/__tests__/unit/middleware/authenticate.test.js
  packages/magiclink-auth-service-api/__tests__/unit/middleware/validate-magiclink-payload.test.js
  packages/magiclink-auth-service-api/__tests__/unit/mocks.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/api-docs.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/index.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/router-mock.js
  packages/magiclink-auth-service-api/__tests__/unit/service/authenticationService.test.js
  packages/magiclink-auth-service-api/__tests__/unit/service/passportWrapper.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/crypto.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/dateUtil.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/jwt.test.js
  packages/magiclink-auth-service-api/__tests__/unit/validators/schema/magicLinkDataValidator.test.js
  packages/magiclink-auth-service-api/jest.config.js
Labels: please-review-me

#1874 feat(as-3873): rename test folder to __test__ to adher to Azure pipel…
  packages/magiclink-auth-service-api/__tests__/integration/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/resources/magicLinkData.json
  packages/magiclink-auth-service-api/__tests__/setup-jest.js
  packages/magiclink-auth-service-api/__tests__/unit/controllers/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/error/apiErrorHandler.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/createAuthToken.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/createMagicLink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/sendMagicLinkEmail.test.js
  packages/magiclink-auth-service-api/__tests__/unit/lib/getYamlAsJson.test.js
  packages/magiclink-auth-service-api/__tests__/unit/mapper/magicLinkTokenMapper.test.js
  packages/magiclink-auth-service-api/__tests__/unit/middleware/authenticate.test.js
  packages/magiclink-auth-service-api/__tests__/unit/middleware/validate-magiclink-payload.test.js
  packages/magiclink-auth-service-api/__tests__/unit/mocks.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/api-docs.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/index.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/router-mock.js
  packages/magiclink-auth-service-api/__tests__/unit/service/authenticationService.test.js
  packages/magiclink-auth-service-api/__tests__/unit/service/passportWrapper.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/crypto.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/dateUtil.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/jwt.test.js
  packages/magiclink-auth-service-api/__tests__/unit/validators/schema/magicLinkDataValidator.test.js
  packages/magiclink-auth-service-api/jest.config.js
Labels: please-review-me

#1852 feat(forms-web-app): added full-planning local-planning-department page
  packages/forms-web-app/__tests__/unit/controllers/before-you-start/local-planning-department.test.js
  packages/forms-web-app/__tests__/unit/lib/views.test.js
  packages/forms-web-app/__tests__/unit/routes/before-you-start/index.test.js
  packages/forms-web-app/__tests__/unit/routes/before-you-start/local-planning-department.test.js
  packages/forms-web-app/__tests__/unit/routes/index.test.js
  packages/forms-web-app/__tests__/unit/validators/before-you-start/local-planning-department.test.js
  packages/forms-web-app/src/controllers/before-you-start/local-planning-department.js
  packages/forms-web-app/src/lib/views.js
  packages/forms-web-app/src/routes/before-you-start/index.js
  packages/forms-web-app/src/routes/before-you-start/local-planning-department.js
  packages/forms-web-app/src/routes/index.js
  packages/forms-web-app/src/validators/before-you-start/local-planning-department.js
  packages/forms-web-app/src/views/before-you-start/local-planning-department.njk
  packages/forms-web-app/src/views/layouts/main-no-back-link.njk
Labels: please-review-me

#1881 revert(clamav): revert clamav commit
  packages/forms-web-app/src/validators/appellant-submission/appeal-statement-schema.js
  packages/forms-web-app/src/validators/appellant-submission/supporting-documents-schema.js
  packages/forms-web-app/src/validators/appellant-submission/upload-application-schema.js
  packages/forms-web-app/src/validators/appellant-submission/upload-decision-schema.js
  packages/lpa-questionnaire-web-app/src/validators/schemas/files.js
Labels: bug, please-review-me

#1891 Update Dockerfile for Magic Link
  packages/magiclink-auth-service-api/Dockerfile
Labels: bug, please-review-me
