Repository Planning-Inspectorate/appeal-planning-decision, pull requests merged in 2021-07, with the labels that each got.

#1346 chore(dev-version-bump): version bump [ci skip]
  releases/dev/app.yml
Labels: please-review-me

#1345 chore(as-2495): deploy fwa 1.47.4 to pre prod
  releases/preprod/app.yml
Labels: please-review-me

#1351 chore(appeal-reply-service-api): version bump [ci skip]
  releases/dev/app.yml
Labels: please-review-me

#1352 chore(lpa-questionnaire-web-app): version bump [ci skip]
  releases/dev/app.yml
Labels: please-review-me

#1353 Chore/web app version bump
  releases/dev/app.yml
Labels: please-review-me

#1341 feat(as-2754): amend content on original applicant question
  e2e-tests/cypress/integration/common/appellant-submission-your-details.js
  e2e-tests/cypress/support/appellant-submission-your-details/confirmWhoAreYouRejectedBecause.js
  e2e-tests/cypress/support/appellant-submission-your-details/provideAnswerNo.js
  e2e-tests/cypress/support/appellant-submission-your-details/provideAnswerYes.js
  packages/forms-web-app/src/controllers/appellant-submission/who-are-you.js
  packages/forms-web-app/src/validators/appellant-submission/who-are-you.js
  packages/forms-web-app/src/views/appellant-submission/who-are-you.njk
  packages/forms-web-app/tests/unit/controllers/appellant-submission/who-are-you.test.js
Labels: draft, please-review-me

#1354 feat: Add mongo GUI app
  docker-compose.yml
Labels: please-review-me

#1357 chore(lpa-questionnaire-web-app): version bump [ci skip]
  releases/dev/app.yml
Labels: please-review-me

#1360 chore(as-2802): deploy fwa 1.51.0 to dev
  releases/dev/app.yml
Labels: please-review-me

#1362 chore(lpa-questionnaire-web-app): version bump [ci skip]
  releases/dev/app.yml
Labels: please-review-me

#1364 chore(as-2889): deploy fwa 1.51.1 to dev
  releases/dev/app.yml
Labels: please-review-me

#1408 fix(as-2754): fix cypress test code
  e2e-tests/cypress/integration/common/appellant-submission-your-details.js
  e2e-tests/cypress/support/appellant-submission-your-details/confirmWhoAreYouRejectedBecause.js
Labels: please-review-me

#1423 chore(lpa-questionnaire-web-app): version bump [ci skip]
  releases/dev/app.yml
Labels: please-review-me

#1430 test: updated tests for invalid file delete
  lpa-submissions-e2e-tests/cypress/integration/common/uploadFiles.js
  lpa-submissions-e2e-tests/cypress/support/PageObjects/common-page-objects.js
  lpa-submissions-e2e-tests/cypress/support/commands.js
  lpa-submissions-e2e-tests/cypress/support/common/validateFileUploadErrorMessage.js
Labels: please-review-me

#1449 fix(as-2831): clamav docker k8s config
  charts/app/templates/formsWebApp.yaml
  charts/app/values.yaml
  docker-compose.yml
  releases/dev/app.yml
Labels: draft

#1456 Subtask/as 3007 revert date input
  packages/lpa-questionnaire-web-app/src/validators/custom/date-input.js
  packages/lpa-questionnaire-web-app/tests/unit/validators/custom/date-input.test.js
Labels: draft

#1462 chore(lpa-questionnaire-web-app-and-appeals-reply-service-api): versi…
  releases/preprod/app.yml
Labels: please-review-me

#1464 fix(lpa-questionnaire-web-app): fix non appearance of appeal-reply-id…
  packages/lpa-questionnaire-web-app/src/controllers/upload-question.js
  packages/lpa-questionnaire-web-app/src/views/includes/head.njk
  packages/lpa-questionnaire-web-app/tests/unit/controllers/upload-question.test.js
Labels: please-review-me

#1473 feat(as-3015): allow harrogate for lpa
  charts/app/templates/lpa.yaml
  packages/appeals-service-api/data/lpa-list.csv
  packages/appeals-service-api/data/lpa-trialists.json
Labels: please-review-me

#1475 chore(as-2836): deploy fwa 1.53.0 to dev
  releases/dev/app.yml
Labels: please-review-me

#1476 chore(lpa-questionnaire-web-app): version bump [ci skip]
  releases/preprod/app.yml
Labels: please-review-me

#1544 Subtask/as 2747 feature file step definitions
  lpa-submissions-e2e-tests/cypress/integration/supplementaryAddDocument/supplementaryAddDocument.step.js
Labels: please-review-me
