Repository Planning-Inspectorate/appeal-planning-decision, pull requests merged in 2022-01, with the labels that each got.

#1969 feat(as-4144): implement content change
  packages/e2e-tests/cypress/integration/full-appeal/eligibility/appellant-selects-the-site/appellant-selects-the-site-steps.js
  packages/forms-web-app/src/views/full-appeal/any-of-following.njk
Labels: enhancement, please-review-me

#1970 feat(full appeal): /submit-appeal/application-number page implemented
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/application-number.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/application-number.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
  packages/forms-web-app/__tests__/unit/validators/full-appeal/application-number.test.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/application-number.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/application-number.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
  packages/forms-web-app/src/services/task.service.js
  packages/forms-web-app/src/validators/full-appeal/application-number.js
  packages/forms-web-app/src/views/full-appeal/submit-appeal/application-number.njk
Labels: please-review-me

#1976 feat(full appeal): /full-appeal/submit-appeal/appeal-site-address implementation
  packages/business-rules/src/schemas/full-appeal/insert.js
  packages/business-rules/src/schemas/full-appeal/insert.test.js
  packages/business-rules/src/schemas/full-appeal/update.js
  packages/business-rules/src/schemas/full-appeal/update.test.js
  packages/business-rules/test/data/full-appeal.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/appeal-site-address.test.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/task-list.test.js
  packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/appeal-site-address.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
  packages/forms-web-app/__tests__/unit/validators/full-appeal/appeal-site-address.test.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/appeal-site-address.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
  packages/forms-web-app/src/lib/full-appeal/views.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/appeal-site-address.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
  packages/forms-web-app/src/services/task.service.js
  packages/forms-web-app/src/validators/full-appeal/appeal-site-address.js
  packages/forms-web-app/src/views/full-appeal/submit-appeal/appeal-site-address.njk
Labels: please-review-me

#1985 feat(full appeal): /full-appeal/submit-appeal/applicant-name implementation
  packages/appeals-service-api/__tests__/unit/value-appeal.js
  packages/appeals-service-api/src/models/appeal.js
  packages/business-rules/src/schemas/full-appeal/insert.js
  packages/business-rules/src/schemas/full-appeal/insert.test.js
  packages/business-rules/src/schemas/full-appeal/update.js
  packages/business-rules/src/schemas/full-appeal/update.test.js
  packages/business-rules/test/data/full-appeal.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/applicant-name.test.js
  packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/applicant-name.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
  packages/forms-web-app/__tests__/unit/validators/full-appeal/applicant-name.test.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/applicant-name.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/task-list.js
  packages/forms-web-app/src/lib/full-appeal/views.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/applicant-name.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
  packages/forms-web-app/src/services/task.service.js
  packages/forms-web-app/src/validators/full-appeal/applicant-name.js
  packages/forms-web-app/src/views/full-appeal/submit-appeal/applicant-name.njk
Labels: please-review-me

#1987 feature: content change for page title
  packages/e2e-tests/cypress/integration/eligibility/full-appeal/appellant-selects-the-site/appellant-selects-the-site-steps.js
  packages/forms-web-app/src/views/full-appeal/any-of-following.njk
Labels: enhancement, please-review-me

#1995 fix(as-4237): remove magic links
  docker-compose.yml
  packages/magiclink-auth-service-api/.eslintignore
  packages/magiclink-auth-service-api/.eslintrc
  packages/magiclink-auth-service-api/Dockerfile
  packages/magiclink-auth-service-api/__tests__/integration/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/resources/magicLinkData.json
  packages/magiclink-auth-service-api/__tests__/setup-jest.js
  packages/magiclink-auth-service-api/__tests__/unit/controllers/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/error/apiErrorHandler.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/createAuthToken.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/createMagicLink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/interactors/sendMagicLinkEmail.test.js
  packages/magiclink-auth-service-api/__tests__/unit/lib/getYamlAsJson.test.js
  packages/magiclink-auth-service-api/__tests__/unit/mapper/magicLinkTokenMapper.test.js
  packages/magiclink-auth-service-api/__tests__/unit/middleware/authenticate.test.js
  packages/magiclink-auth-service-api/__tests__/unit/middleware/validate-magiclink-payload.test.js
  packages/magiclink-auth-service-api/__tests__/unit/mocks.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/api-docs.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/index.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/magiclink.test.js
  packages/magiclink-auth-service-api/__tests__/unit/routes/router-mock.js
  packages/magiclink-auth-service-api/__tests__/unit/service/authenticationService.test.js
  packages/magiclink-auth-service-api/__tests__/unit/service/passportWrapper.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/crypto.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/dateUtil.test.js
  packages/magiclink-auth-service-api/__tests__/unit/util/jwt.test.js
  packages/magiclink-auth-service-api/__tests__/unit/validators/schema/magicLinkDataValidator.test.js
  packages/magiclink-auth-service-api/api/openapi.yaml
  packages/magiclink-auth-service-api/azure-magic-link-web-app-build.yml
  packages/magiclink-auth-service-api/jest.config.js
  packages/magiclink-auth-service-api/lib/getYamlAsJson.js
  packages/magiclink-auth-service-api/package-lock.json
  packages/magiclink-auth-service-api/package.json
  packages/magiclink-auth-service-api/src/app.js
  packages/magiclink-auth-service-api/src/config.js
  packages/magiclink-auth-service-api/src/controllers/magiclink.js
  packages/magiclink-auth-service-api/src/error/apiError.js
  packages/magiclink-auth-service-api/src/error/apiErrorHandler.js
  packages/magiclink-auth-service-api/src/interactors/createAuthToken.js
  packages/magiclink-auth-service-api/src/interactors/createMagicLink.js
  packages/magiclink-auth-service-api/src/interactors/sendMagicLinkEmail.js
  packages/magiclink-auth-service-api/src/mappers/magicLinkTokenMapper.js
  packages/magiclink-auth-service-api/src/middleware/authenticate.js
  packages/magiclink-auth-service-api/src/middleware/validate-magiclink-payload.js
  packages/magiclink-auth-service-api/src/routes/api-docs.js
  packages/magiclink-auth-service-api/src/routes/index.js
  packages/magiclink-auth-service-api/src/routes/magiclink.js
  packages/magiclink-auth-service-api/src/server.js
  packages/magiclink-auth-service-api/src/service/authenticationService.js
  packages/magiclink-auth-service-api/src/service/error/ExpiredTokenError.js
  packages/magiclink-auth-service-api/src/service/error/InvalidTokenError.js
  packages/magiclink-auth-service-api/src/service/passportWrapper.js
  packages/magiclink-auth-service-api/src/util/crypto.js
  packages/magiclink-auth-service-api/src/util/dateUtil.js
  packages/magiclink-auth-service-api/src/util/jwt.js
  packages/magiclink-auth-service-api/src/util/logger.js
  packages/magiclink-auth-service-api/src/validators/schema/magiclinkDataValidator.js
Labels: draft

#1999 fix(as-4237): remove magic links
  packages/lpa-questionnaire-web-app/__tests__/unit/auth/passportWrapper.test.js
  packages/lpa-questionnaire-web-app/__tests__/unit/controllers/development-plan.test.js
  packages/lpa-questionnaire-web-app/__tests__/unit/controllers/supplementary-documents/delete-supplementary-document.test.js
  packages/lpa-questionnaire-web-app/__tests__/unit/lib/magiclink-api-wrapper.test.js
  packages/lpa-questionnaire-web-app/__tests__/unit/middleware/authenticate.test.js
  packages/lpa-questionnaire-web-app/__tests__/unit/services/authentication/authentication.service.test.js
  packages/lpa-questionnaire-web-app/__tests__/unit/services/authentication/passportWrapper.test.js
  packages/lpa-questionnaire-web-app/src/config.js
  packages/lpa-questionnaire-web-app/src/controllers/authentication.js
  packages/lpa-questionnaire-web-app/src/lib/magiclink-api-wrapper.js
  packages/lpa-questionnaire-web-app/src/middleware/authenticate.js
  packages/lpa-questionnaire-web-app/src/middleware/check-if-supplementary-documents.js
  packages/lpa-questionnaire-web-app/src/public/js/govuk.js
  packages/lpa-questionnaire-web-app/src/routes/already-submitted.js
  packages/lpa-questionnaire-web-app/src/services/authentication/authentication.service.js
  packages/lpa-questionnaire-web-app/src/services/authentication/error/ExpiredTokenError.js
  packages/lpa-questionnaire-web-app/src/services/authentication/error/InvalidTokenError.js
  packages/lpa-questionnaire-web-app/src/services/authentication/passportWrapper.js
  packages/lpa-questionnaire-web-app/src/validators/email.js
Labels: draft

#1996 feat(as-3652): Navigate to limited-building-householder page when householder application type is chosen
  packages/e2e-tests/cypress/integration/eligibility/full-appeal/planning-application-type/planning-application-type-steps.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/type-of-planning-application.test.js
  packages/forms-web-app/src/controllers/full-appeal/type-of-planning-application.js
Labels: please-review-me, team2

#1998 feat(full appeal): /full-appeal/submit-appeal/original-applicant implementation
  packages/business-rules/src/schemas/full-appeal/insert.js
  packages/business-rules/src/schemas/full-appeal/insert.test.js
  packages/business-rules/src/schemas/full-appeal/update.js
  packages/business-rules/src/schemas/full-appeal/update.test.js
  packages/business-rules/test/data/full-appeal.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/original-applicant.test.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/task-list.test.js
  packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/original-applicant.test.js
  packages/forms-web-app/__tests__/unit/validators/full-appeal/original-applicant.test.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/applicant-name.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/original-applicant.js
  packages/forms-web-app/src/lib/full-appeal/views.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/original-applicant.js
  packages/forms-web-app/src/services/task.service.js
  packages/forms-web-app/src/validators/full-appeal/original-applicant.js
  packages/forms-web-app/src/views/full-appeal/submit-appeal/original-applicant.njk
Labels: please-review-me

#2004 feat(as-3637): remove page hint
  packages/forms-web-app/src/views/full-appeal/date-decision-due.njk
Labels: please-review-me, team2

#2002 feat(as-3638): remove page hint
  packages/forms-web-app/src/views/full-appeal/enforcement-notice.njk
  packages/forms-web-app/src/views/householder-planning/eligibility/enforcement-notice-householder.njk
Labels: please-review-me, team2

#2017 fix(full appeal): applicant-name next page fix
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/applicant-name.test.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/applicant-name.js
Labels: please-review-me

#2047 fix: fixed tests and updated the issue with decision date
  packages/e2e-tests/cypress/integration/eligibility/householder-planning/date-decision-due/date-decision-due-steps.js
  packages/e2e-tests/cypress/support/eligibility/page-objects/shutter-page-po.js
  packages/forms-web-app/src/controllers/householder-planning/eligibility/date-decision-due-householder.js
Labels: please-review-me

#2049 feat(full appeal): /full-appeal/submit-appeal/declaration page
  docker-compose.yml
  packages/appeals-service-api/__tests__/unit/lib/full-appeal/notify.test.js
  packages/appeals-service-api/__tests__/unit/services/appeal.service.test.js
  packages/appeals-service-api/src/constants.js
  packages/appeals-service-api/src/lib/config.js
  packages/appeals-service-api/src/lib/full-appeal/notify.js
  packages/appeals-service-api/src/services/appeal.service.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/appeal-submitted.test.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/declaration-information.test.js
  packages/forms-web-app/__tests__/unit/controllers/full-appeal/submit-appeal/declaration.test.js
  packages/forms-web-app/__tests__/unit/lib/full-appeal/views.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/appeal-submitted.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/declaration-information.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/declaration.test.js
  packages/forms-web-app/__tests__/unit/routes/full-appeal/submit-appeal/index.test.js
  packages/forms-web-app/__tests__/unit/services/pdf.service.test.js
  packages/forms-web-app/src/constants.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/appeal-submitted.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration-information.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
  packages/forms-web-app/src/lib/full-appeal/views.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/appeal-submitted.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/declaration-information.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/declaration.js
  packages/forms-web-app/src/routes/full-appeal/submit-appeal/index.js
  packages/forms-web-app/src/services/pdf.service.js
  packages/forms-web-app/src/views/full-appeal/submit-appeal/appeal-submitted.njk
  packages/forms-web-app/src/views/full-appeal/submit-appeal/declaration-information.njk
  packages/forms-web-app/src/views/full-appeal/submit-appeal/declaration.njk
Labels: please-review-me

#2128 fix(as-1234): security updates appeal service api
  packages/appeals-service-api/package-lock.json
  packages/appeals-service-api/package.json
Labels: draft

#2134 feat(as-4403): View householder appeal task list
  packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs.feature
  packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs/claiming-costs-steps.js
  packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/claiming-costs-householder.test.js
  packages/forms-web-app/src/controllers/householder-planning/eligibility/claiming-costs-householder.js
Labels: please-review-me, team2

#2140 fix(full appeal): confirmation email is using data from contact details
  packages/appeals-service-api/__tests__/unit/lib/full-appeal/notify.test.js
  packages/appeals-service-api/src/lib/full-appeal/notify.js
  packages/forms-web-app/src/controllers/full-appeal/submit-appeal/declaration.js
Labels: please-review-me

#2144 fix(as-4478): fixed back link issue at householder claiming cost page
  packages/e2e-tests/cypress/integration/eligibility/householder-planning/claiming-costs/claiming-costs-steps.js
  packages/forms-web-app/__tests__/unit/controllers/householder-planning/eligibility/claiming-costs-householder.test.js
  packages/forms-web-app/src/controllers/householder-planning/eligibility/claiming-costs-householder.js
Labels: please-review-me, team2
